############################## AUTH ##############################
@baseUrl = http://localhost:1234/api
### Register User
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Angel",
  "email": "angeldaniemf+owner@gmail.com",
  "password": "password123"
}

### Verify Email
GET {{baseUrl}}/verify-email?token=ba4c968fc47d3b629688504cf5fcb65cccb1e4c14a5583ba5a232d973639f1e7

### Login User
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "angeldaniemf+owner@gmail.com",
  "password": "password123"
}

### Logout
POST {{baseUrl}}/logout

### Refresh Token
POST {{baseUrl}}/refresh-token


###GET Me
GET {{baseUrl}}/me

############################## ORGANIZATION ##############################

### Create Org
POST {{baseUrl}}/organizations/create
Content-Type: application/json

{
  "name": "My Organization"
}

### Get My Orgs
GET {{baseUrl}}/organizations/my

### Get Org by ID
GET {{baseUrl}}/organizations/79d4e29f-6964-45b4-a676-3727ad34cefb

### delete Org
DELETE {{baseUrl}}/organizations/79d4e29f-6964-45b4-a676-3727ad34cefb

### Invite User to Org
POST {{baseUrl}}/organizations/79d4e29f-6964-45b4-a676-3727ad34cefb/invite
Content-Type: application/json

{
  "email": "angeldaniemf+member2@gmail.com",
  "role": "member"
}

### Get Invite Info
GET {{baseUrl}}/organizations/invite/ca8f3c2b94532c78b408146248685be853486090b445793c4fb9a9fd9522ad24
### Accept Invite
POST {{baseUrl}}/organizations/invite/ca8f3c2b94532c78b408146248685be853486090b445793c4fb9a9fd9522ad24/accept

############################## MEMBERS ##############################

### GET Members
GET {{baseUrl}}/members/79d4e29f-6964-45b4-a676-3727ad34cefb

### PATCH Update Member Role
PATCH {{baseUrl}}/members/79d4e29f-6964-45b4-a676-3727ad34cefb/7d73a753-1e39-446f-8b3b-08e65a61dda7
Content-Type: application/json

{
  "role": "member"
}

### DELETE Remove Member
DELETE {{baseUrl}}/members/:orgId/:memberId

### GET Member Balance
GET {{baseUrl}}/members/:orgId/:memberId/balance

############################## TRANSACTIONS ##############################

### Reward Member
POST {{baseUrl}}/transactions/79d4e29f-6964-45b4-a676-3727ad34cefb/reward/2377a961-863a-48f0-92e2-446eadecb7f8
Content-Type: application/json

{
  "amount": 100,
  "message": "Great job on the project!"
}

### Transfer Points
POST {{baseUrl}}/transactions/79d4e29f-6964-45b4-a676-3727ad34cefb/transfer/:memberId
Content-Type: application/json

{
  "amount": 50,
  "message": "Thanks for your help!"
}

### Get Org Trasnsactions
GET {{baseUrl}}/transactions/:orgId

### Get My Transactions
GET {{baseUrl}}/transactions/:orgId/me