############################## AUTH ##############################
@baseUrl = http://localhost:1234/api
### Register User
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Daniel",
  "email": "angeldaniemf+member4@gmail.com",
  "password": "password123"
}

### Verify Email
GET {{baseUrl}}/verify-email?token=b1871e927483c7cde33d11043c2c7ddcbb3b9eb61dc592d559e7e4e17be2e763

### Login User
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "angeldaniemf+owner@gmail.com",
  "password": "password123"
}

### Logout
POST {{baseUrl}}/logout

### Refresh Token
POST {{baseUrl}}/refresh-token


###GET Me
GET {{baseUrl}}/me

############################## ORGANIZATION ##############################

### Create Org
POST {{baseUrl}}/organizations/create
Content-Type: application/json

{
  "name": "My Organization"
}

### Get My Orgs
GET {{baseUrl}}/organizations/my

### Get Org by ID
GET {{baseUrl}}/organizations/79d4e29f-6964-45b4-a676-3727ad34cefb

### delete Org
DELETE {{baseUrl}}/organizations/1c8c0b4d-7e61-493f-b8f0-4a0ec5cb4ae4

### Invite User to Org
POST {{baseUrl}}/organizations/79d4e29f-6964-45b4-a676-3727ad34cefb/invite
Content-Type: application/json

{
  "email": "angeldaniemf+member4@gmail.com",
  "role": "member"
}

### Get Invite Info
GET {{baseUrl}}/organizations/invite/ca8f3c2b94532c78b408146248685be853486090b445793c4fb9a9fd9522ad24
### Accept Invite
POST {{baseUrl}}/organizations/invite/e53764feda56dda991cc5bfd4df0c6b9d462efe77d64f7a2bce117d59b7e75b6/accept

############################## MEMBERS ##############################

### GET Members
GET {{baseUrl}}/members/79d4e29f-6964-45b4-a676-3727ad34cefb

### PATCH Update Member Role
PATCH {{baseUrl}}/members/79d4e29f-6964-45b4-a676-3727ad34cefb/7d73a753-1e39-446f-8b3b-08e65a61dda7
Content-Type: application/json

{
  "role": "member"
}

### DELETE Remove Member
DELETE {{baseUrl}}/members/79d4e29f-6964-45b4-a676-3727ad34cefb/4b221498-e240-4e8c-9473-8528854c5790

### GET Member Balance
GET {{baseUrl}}/members/:orgId/:memberId/balance

############################## TRANSACTIONS ##############################

### Reward Member
POST {{baseUrl}}/transactions/79d4e29f-6964-45b4-a676-3727ad34cefb/reward/6a47b32d-79d1-47fc-8869-89c275abe19b
Content-Type: application/json

{
  "amount": 100,
  "message": "Great job on the project!"
}

### Transfer Points
POST {{baseUrl}}/transactions/79d4e29f-6964-45b4-a676-3727ad34cefb/transfer/7d73a753-1e39-446f-8b3b-08e65a61dda7
Content-Type: application/json

{
  "amount": 50,
  "message": "Thanks for your help!"
}

### Get Org Trasnsactions
GET {{baseUrl}}/transactions/79d4e29f-6964-45b4-a676-3727ad34cefb

### Get My Transactions
GET {{baseUrl}}/transactions/79d4e29f-6964-45b4-a676-3727ad34cefb/me